### ISSUE TITLE
Distorted display of the grid-api on IE 11

### ISSUE THREAD

**Issue by dosindi** [Artur-/grid-api#1]
![improper_display](https://cloud.githubusercontent.com/assets/1564400/11140241/6b442616-89e9-11e5-8035-5009fe0c7463.png)

I came across this issue, is there any way of address it, for the grid to display properly on IE11?

**Comment by Artur-** [comment]
Not likely an issue in this test application :)

Try updating to 7.5.9 which fixes https://dev.vaadin.com/ticket/18820
